name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deno-fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: denoland/setup-deno@v2
        with:
          cache: true

      - name: Run deno fmt
        run: deno fmt --check

  deno-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: denoland/setup-deno@v2
        with:
          cache: true

      - name: Run deno lint
        run: deno lint

  rust-fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Run cargo fmt
        run: cargo fmt --check

  rust-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Start MySQL container (reqired for sqlx compile-time checks)
        run: docker compose up --detach db

      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2

      - name: Install sqlx CLI
        run: cargo install sqlx-cli

      - uses: denoland/setup-deno@v2

      - name: Run migrations
        run: deno task migrate

      - name: Run cargo clippy
        run: cargo clippy -- --deny warnings
